<?php
// $Id: themekey_debug.install,v 1.2.2.1 2010/08/16 13:35:14 mkalkbrenner Exp $

/**
 * @file
 * Cleans up variables when unistalling
 * @see themekey_debug.module
 *
 * @author Markus Kalkbrenner | Cocomore AG
 *   @see http://drupal.org/user/124705
 */


/**
 * Implements hook_uninstall().
 */
function themekey_debug_uninstall() {
  // Remove variables
  db_query("DELETE FROM {variable} WHERE name LIKE 'themekey_debug_%%'");
  cache_clear_all('variables', 'cache');
}
